DROP TABLE FAIT_TURNOVER;
DROP TABLE FAIT_PROPORTION;
DROP TABLE FAIT_COTE;
DROP TABLE FAIT_POPULARITE;
DROP TABLE FAIT_MOYNOTES;
DROP TABLE FAIT_NBJOURSPROJ;
DROP TABLE DIM_ANNEE;
DROP TABLE DIM_MOIS;
DROP TABLE DIM_SEMAINE;
DROP TABLE DIM_JOUR;
DROP TABLE DIM_PERIODE;
DROP TABLE DIM_MOVIE;
DROP TABLE DIM_PAYS;
DROP TABLE DIM_COMPLEXE;
DROP TABLE DIM_SALLE;
DROP TABLE DIM_GENRE;
DROP SEQUENCE SEQLOGS;

CREATE SEQUENCE SEQLOGS;

CREATE TABLE Logs
(
	idLogs VARCHAR2(20) CONSTRAINT PKLogs PRIMARY KEY,
	LogWhen TIMESTAMP CONSTRAINT NN_LogsWhen NOT NULL,
	ErrorCode VARCHAR2(10),
	LogWhat VARCHAR2(4000) CONSTRAINT NN_LogsWhat NOT NULL, 
	Logwhere VARCHAR2(100) CONSTRAINT NN_LogsWhere NOT NULL
);

CREATE TABLE DIM_GENRE
(
	GENRE VARCHAR2(20) CONSTRAINT PK_DIM_GENRE PRIMARY KEY
);

CREATE TABLE DIM_SALLE
(
	SALLE NUMBER CONSTRAINT PK_DIM_SALLE PRIMARY KEY
);

CREATE TABLE DIM_COMPLEXE
(
	COMPLEXE VARCHAR2(100) CONSTRAINT PK_DIM_COMPLEXE PRIMARY KEY
);

CREATE TABLE DIM_PAYS
(
	PAYS VARCHAR2(35) CONSTRAINT PK_DIM_PAYS PRIMARY KEY
);

CREATE TABLE DIM_MOVIE
(
	MOVIE NUMBER CONSTRAINT PK_DIM_FILM PRIMARY KEY
);

CREATE TABLE DIM_PERIODE
(
	PERIODE VARCHAR2(10) CONSTRAINT PK_DIM_PERIODE PRIMARY KEY
);

CREATE TABLE DIM_JOUR
(
	JOUR NUMBER CONSTRAINT PK_DIM_JOUR PRIMARY KEY
);

CREATE TABLE DIM_SEMAINE
(
	SEMAINE NUMBER CONSTRAINT PK_DIM_SEMAINE PRIMARY KEY
);

CREATE TABLE DIM_MOIS
(
	MOIS DATE CONSTRAINT PK_DIM_MOIS PRIMARY KEY
);

CREATE TABLE DIM_ANNEE
(
	ANNEE DATE CONSTRAINT PK_DIM_ANNEE PRIMARY KEY
);

CREATE TABLE FAIT_NBJOURSPROJ
(
	NATIONALITE		VARCHAR2(35) CONSTRAINT REF_DIM_PAYS_NJP REFERENCES DIM_PAYS(PAYS),
	NBJOURSPROJ 	NUMBER
);

CREATE TABLE FAIT_MOYNOTES
(
	NATIONALITE	VARCHAR2(35) CONSTRAINT REF_DIM_PAYS_MN REFERENCES DIM_PAYS(PAYS),
	MOYNOTES 	NUMBER
);

CREATE TABLE FAIT_POPULARITE
(
	GENRE		VARCHAR2(20) CONSTRAINT REF_DIM_GENRE_PO REFERENCES DIM_GENRE(GENRE),
	SALLE		NUMBER CONSTRAINT REF_DIM_SALLE_PO REFERENCES DIM_SALLE(SALLE),
	PERIODE		VARCHAR2(10) CONSTRAINT REF_DIM_PERIODE_PO REFERENCES DIM_PERIODE(PERIODE),
	JOUR		NUMBER CONSTRAINT REF_DIM_JOUR_PO REFERENCES DIM_JOUR(JOUR),
	SEMAINE		NUMBER CONSTRAINT REF_DIM_SEMAINE_PO REFERENCES DIM_SEMAINE(SEMAINE),
	MOIS		DATE CONSTRAINT REF_DIM_MOIS_PO REFERENCES DIM_MOIS(MOIS),
	POPULARITE	NUMBER
);

CREATE TABLE FAIT_COTE
(
	MOVIE			NUMBER CONSTRAINT REF_DIM_FILM_C REFERENCES DIM_MOVIE(MOVIE),
	NBJOURSPROJ		NUMBER,
	COTE 			NUMBER
);

CREATE TABLE FAIT_PROPORTION
(
	SALLE		NUMBER CONSTRAINT REF_DIM_SALLE_PR REFERENCES DIM_SALLE(SALLE),
	COMPLEXE	VARCHAR2(100) CONSTRAINT REF_DIM_COMPLEXE_PR REFERENCES DIM_COMPLEXE(COMPLEXE),
	MOIS		DATE CONSTRAINT REF_DIM_MOIS_PR REFERENCES DIM_MOIS(MOIS),
	ANNEE		DATE CONSTRAINT REF_DIM_ANNEE_PR REFERENCES DIM_ANNEE(ANNEE),
	PROPORTION	NUMBER
);

CREATE TABLE FAIT_TURNOVER
(
	GENRE		VARCHAR2(20) CONSTRAINT REF_DIM_GENRE_T REFERENCES DIM_GENRE(GENRE),
	SEMAINE		NUMBER CONSTRAINT REF_DIM_SEMAINE_T REFERENCES DIM_SEMAINE(SEMAINE),
	ANNEE		DATE CONSTRAINT REF_DIM_ANNEE_T REFERENCES DIM_ANNEE(ANNEE),
	PAYS		VARCHAR2(35) CONSTRAINT REF_DIM_PAYS_T REFERENCES DIM_PAYS(PAYS),
	TURNOVER	NUMBER
);

