/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rechevalfilm;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author Julien
 */
public class AddOpinionForm extends javax.swing.JDialog
{
    private String Login;
    private String IdMovie;
    private boolean NewQuotation = false;
    private MainForm _MainForm;
    
    /**
     * Creates new form AddOpinionForm
     */
    public AddOpinionForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public AddOpinionForm(java.awt.Frame parent, boolean modal, String IdMovie, String Login) {
        super(parent, modal);
        initComponents();
        setMainForm((MainForm)parent);
        this.Login = Login;
        this.IdMovie = IdMovie;
        SpinnerModel sm = new SpinnerNumberModel(-1, -1, 10, 1);
        spnCote.setModel(sm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnCote = new javax.swing.JSpinner();
        btnAjouter = new javax.swing.JButton();
        lblAvis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarAvis = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        lblAvis.setText("Qu'avez-vous pensé de ce film ?");

        txtarAvis.setColumns(20);
        txtarAvis.setRows(5);
        jScrollPane1.setViewportView(txtarAvis);

        jLabel1.setText("Votre cote");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvis)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(spnCote, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 208, Short.MAX_VALUE)
                        .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnCote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjouter))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        int spnValue = (int)spnCote.getValue();
        if(spnValue > -1 || !txtarAvis.getText().isEmpty())
        {
            try
            {
                getMainForm().getBean().ProcedureStockee("EvalFilm", "AddQuotationOpinion", 4);

                getMainForm().getBean().csSetString(1, IdMovie);
                getMainForm().getBean().csSetString(2, Login);

                System.out.println("Valeur de spnValue = " + spnValue);
                if(spnValue == -1)
                    getMainForm().getBean().csSetNull(3, OracleTypes.NUMBER);
                else
                    getMainForm().getBean().csSetInt(3, spnValue);

                if(!txtarAvis.getText().isEmpty())
                    getMainForm().getBean().csSetString(4, txtarAvis.getText());
                else
                    getMainForm().getBean().csSetNull(4, OracleTypes.VARCHAR);

                getMainForm().getBean().csProcedureExecute();
                NewQuotation = true;
                this.dispose();
            }
            catch (SQLException ex)
            {
                if(ex.getErrorCode() == 20999)
                {
                    getMainForm().DatabaseConnection();
                    JOptionPane.showMessageDialog(this, "Une petite erreur transitoire est survenue ... Veuillez réinserer votre avis !", "Erreur transitoire", JOptionPane.INFORMATION_MESSAGE);
                }
                else
                    Logger.getLogger(AddOpinionForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Vous devez au moins insérer une cote ou un avis !", "Erreur", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOpinionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOpinionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOpinionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOpinionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddOpinionForm dialog = new AddOpinionForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAvis;
    private javax.swing.JSpinner spnCote;
    private javax.swing.JTextArea txtarAvis;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the NewQuotation
     */
    public boolean isNewQuotation() {
        return NewQuotation;
    }

    /**
     * @return the _MainForm
     */
    public MainForm getMainForm() {
        return _MainForm;
    }

    /**
     * @param _MainForm the _MainForm to set
     */
    public void setMainForm(MainForm _MainForm) {
        this._MainForm = _MainForm;
    }
}
