/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rechevalfilm;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author Julien
 */
public class AvisForm extends javax.swing.JDialog {

    private String IdMovie;
    private Integer i = 0;
    private int PageCourante = 1;
    private short NombreAvisCotes;
    private float NombrePages;
    private MainForm _MainForm;
    
    public AvisForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public AvisForm(java.awt.Frame parent, boolean modal, String IdMovie, short NombreAvisCotes)
    {
        super(parent, modal);
        initComponents();
        this.IdMovie = IdMovie;
        setMainForm((MainForm)parent);
        lblNumero.setText(String.valueOf(PageCourante));
        this.NombreAvisCotes = NombreAvisCotes;
        NombrePages = this.NombreAvisCotes / (float)5;
        FillTable();
    }
    
    private void FillTable()
    {
        try 
        {
            getMainForm().getBean().FonctionStockee("RechFilm", "GetQuotationsOpinionsFromRQS", 2);
            
            getMainForm().getBean().csRegisterOutParameter(1, OracleTypes.CURSOR);
            getMainForm().getBean().csSetString(2, IdMovie);
            getMainForm().getBean().csSetInt(3, i);
            ResultSet rs = getMainForm().getBean().csFonctionExecute();
            DefaultTableModel dtm = (DefaultTableModel)tblCotesAvis.getModel();
            ClearTable();
            while(rs.next())
                dtm.addRow(new Object[] { rs.getString("Login"), rs.getString("Opinion"), rs.getInt("Quotation"), rs.getDate("DateOfPost").toString()});
        } 
        catch (SQLException ex)
        {
            if(ex.getErrorCode() == 20999)
                getMainForm().DatabaseConnection();
            else
                Logger.getLogger(AddOpinionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void ClearTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblCotesAvis.getModel();
        int rowCount = dtm.getRowCount();
        for (int j = rowCount - 1; j >= 0; j--)
            dtm.removeRow(j);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumero = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCotesAvis = new javax.swing.JTable();
        btnPrecedents = new javax.swing.JButton();
        btnSuivants = new javax.swing.JButton();
        lblPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNumero.setText("jLabel1");

        tblCotesAvis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Login", "Avis", "Cote", "Date of post"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCotesAvis);

        btnPrecedents.setText("<< Précédent");
        btnPrecedents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentsActionPerformed(evt);
            }
        });

        btnSuivants.setText("Suivant >>");
        btnSuivants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantsActionPerformed(evt);
            }
        });

        lblPage.setText("Page numéro : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPrecedents)
                        .addGap(300, 300, 300)
                        .addComponent(lblPage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSuivants)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrecedents)
                    .addComponent(btnSuivants)
                    .addComponent(lblPage)
                    .addComponent(lblNumero))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrecedentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentsActionPerformed
        if(PageCourante > 1)
        {
            i--;
            PageCourante--;
            lblNumero.setText(String.valueOf(PageCourante));
            FillTable();
        }
    }//GEN-LAST:event_btnPrecedentsActionPerformed

    private void btnSuivantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantsActionPerformed
        if(PageCourante < NombrePages)
        {
            i++;
            PageCourante++;
            lblNumero.setText(String.valueOf(PageCourante));
            FillTable();
        }
    }//GEN-LAST:event_btnSuivantsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvisForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AvisForm dialog = new AvisForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrecedents;
    private javax.swing.JButton btnSuivants;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPage;
    private javax.swing.JTable tblCotesAvis;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the _MainForm
     */
    public MainForm getMainForm() {
        return _MainForm;
    }

    /**
     * @param _MainForm the _MainForm to set
     */
    public void setMainForm(MainForm _MainForm) {
        this._MainForm = _MainForm;
    }
}
