BEGIN
	DBMS_SCHEDULER.CREATE_JOB
	(
		JOB_NAME => 'JOB_ALIMCC',
		JOB_TYPE => 'STORED_PROCEDURE',
		JOB_ACTION => 'ALIMCC.JOBALIMCC',
		START_DATE => SYSTIMESTAMP,
		REPEAT_INTERVAL => 'FREQ=WEEKLY;BYHOUR=0;BYMINUTE=0;BYSECOND=0;',
		ENABLED => TRUE,
		COMMENTS => 'Job AlimCC'
	);

EXCEPTION
	WHEN OTHERS THEN RAISE;

END;