CREATE ROLE MYROLE NOT IDENTIFIED;
GRANT ALTER SESSION TO MYROLE;
GRANT CREATE DATABASE LINK TO MYROLE;
GRANT CREATE ANY DIRECTORY TO MYROLE;
GRANT CREATE SESSION TO MYROLE;
GRANT CREATE PROCEDURE TO MYROLE;
GRANT CREATE SEQUENCE TO MYROLE;
GRANT CREATE TABLE TO MYROLE;
GRANT CREATE TRIGGER TO MYROLE;
GRANT CREATE TYPE TO MYROLE;
GRANT CREATE SYNONYM TO MYROLE;
GRANT CREATE VIEW TO MYROLE;
GRANT CREATE JOB TO MYROLE;
GRANT CREATE MATERIALIZED VIEW TO MYROLE;
GRANT EXECUTE ON SYS.DBMS_LOCK TO MYROLE;
GRANT EXECUTE ON SYS.OWA_OPT_LOCK TO MYROLE;
GRANT EXECUTE ON UTL_FILE TO PUBLIC;

CREATE USER CB IDENTIFIED BY CB123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER CB QUOTA UNLIMITED ON USERS;
GRANT MYROLE TO CB;

CREATE USER CBB IDENTIFIED BY CBB123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER CBB QUOTA UNLIMITED ON USERS;
GRANT MYROLE TO CBB;

CREATE USER CC IDENTIFIED BY CC123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER CC QUOTA UNLIMITED ON USERS;
GRANT MYROLE TO CC;

CREATE USER MKT IDENTIFIED BY MKT123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER MKT QUOTA UNLIMITED ON USERS;
GRANT MYROLE TO MKT;

CREATE USER DW IDENTIFIED BY DW123 DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
ALTER USER DW QUOTA UNLIMITED ON USERS;
GRANT MYROLE TO DW;


create or replace directory MOVIES as 'D:\InstallRQS\Movies';

grant read, write on directory MOVIES to CB;

create or replace directory REPXML as 'D:\InstallRQS\CreaCC';

grant read, write on directory REPXML to CC;

GRANT SELECT ON DBA_USERS TO CBB;