BEGIN
	DBMS_SCHEDULER.CREATE_JOB
	(
		JOB_NAME => 'JOB_ARCHPROG',
		JOB_TYPE => 'STORED_PROCEDURE',
		JOB_ACTION => 'ARCHPROG',
		START_DATE => SYSTIMESTAMP,
		REPEAT_INTERVAL => 'FREQ=DAILY;BYHOUR=0;BYMINUTE=0;BYSECOND=0;',
		ENABLED => TRUE,
		COMMENTS => 'Archivage'
	);

EXCEPTION
	WHEN OTHERS THEN RAISE;

END;