create or replace PACKAGE CrashCB AS
	TYPE R_Crash IS RECORD
	(
		SID gv$session.sid%TYPE,
		SERIALNUMBER gv$session.serial#%TYPE
	);
	
	TYPE T_Crash IS TABLE OF R_Crash INDEX BY PLS_INTEGER;
	
	PROCEDURE GetInfos(P_USERNAME IN VARCHAR2);
	PROCEDURE DisconnectSession(P_USERNAME IN VARCHAR2, P_TABCRASH T_CRASH);
	PROCEDURE LockAccount(P_USERNAME IN VARCHAR2);
	PROCEDURE UnlockAccount(P_USERNAME IN VARCHAR2);
END CrashCB;
/