create or replace PACKAGE RechFilm AS 
  
	TYPE R_Logs IS RECORD
	(
		Id Logs.idLogs%TYPE,
		LogWhen Logs.LogWhen%TYPE,
		ErrorCode Logs.ErrorCode%TYPE,
		LogWhat Logs.LogWhat%TYPE,
		LogWhere Logs.LogWhere%TYPE
	);

	PROCEDURE AddLogs(ElemToAdd IN R_Logs);
	FUNCTION Connexion(P_LOGIN IN Users.Login%TYPE) RETURN SYS_REFCURSOR;
	FUNCTION GetMovie(P_IDMOVIE IN Movies.idMovie%TYPE) RETURN SYS_REFCURSOR;
	FUNCTION GetMovies(P_TITLE IN Movies.Title%TYPE, P_ACTORS IN T_ARRAY_NAME, P_DIRECTORS IN T_ARRAY_NAME, P_ANNEEAVANT IN VARCHAR2, P_ANNEEAPRES IN VARCHAR2) RETURN SYS_REFCURSOR;
	FUNCTION GetActorsFromMovie(P_IDMOVIE IN Movies.idMovie%TYPE) RETURN SYS_REFCURSOR;
	FUNCTION GetDirectorsFromMovie(P_IDMOVIE IN Movies.idMovie%TYPE) RETURN SYS_REFCURSOR;
	FUNCTION GetPoster(P_IDPOSTER IN Posters.idPoster%TYPE) RETURN SYS_REFCURSOR;
	FUNCTION GetQuotationsOpinionsFromRQS(P_IDMOVIE IN Movies.idMovie%TYPE) RETURN SYS_REFCURSOR;
	FUNCTION GetQuotationsOpinionsFromRQS(P_IDMOVIE IN Movies.idMovie%TYPE, P_PAGE IN INTEGER) RETURN SYS_REFCURSOR;
END RechFilm;
/