/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rechevalfilm;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import oracle.jdbc.OracleTypes;

/**
 *
 * @author Julien
 */
public class DetailsMovieForm extends javax.swing.JDialog 
{
    private String IdMovie;
    private String Login;
    private short NombreCotesAvis = 0;
    private MainForm Caller;
    /**
     * Creates new form DetailsMovieForm
     */
    public DetailsMovieForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public DetailsMovieForm(java.awt.Frame parent, boolean modal, String IdMovie, String Login) {
        super(parent, modal);
        initComponents();
        this.IdMovie = IdMovie;
        this.Login = Login;
        Caller = (MainForm) parent;
        FillFields();
    }
    
    private void FillFields()
    {
        try 
        {
            /* Infos du films */
            Caller.getBean().FonctionStockee("RechFilm", "GetMovie", 1);
            Caller.getBean().csRegisterOutParameter(1, OracleTypes.CURSOR);
            Caller.getBean().csSetString(2, IdMovie);
            ResultSet rs = Caller.getBean().csFonctionExecute();
            while(rs.next())
            {
                lblId.setText(IdMovie);
                lblRuntime.setText(rs.getString("Runtime"));
                txtarOverview.setLineWrap(true);
                txtarOverview.setText(rs.getString("Overview"));
                lblTitre.setText(rs.getString("Title"));
                lblDate.setText(rs.getDate(3).toString());
                lblMoyenneTMDB.setText(rs.getString("Vote_average"));
                lblNombreTMDB.setText(rs.getString("Vote_count"));
                lblPoster.setIcon(new ImageIcon(rs.getBytes("Poster_path")));
            }
            
            /* Les acteurs */
            Caller.getBean().FonctionStockee("RechFilm", "GetActorsFromMovie", 1);
            Caller.getBean().csRegisterOutParameter(1, OracleTypes.CURSOR);
            Caller.getBean().csSetString(2, IdMovie);
            rs = Caller.getBean().csFonctionExecute();
            
            while(rs.next())
                tfdActeurs.setText(rs.getString(2));
            
            /* Les réalisateurs */
            Caller.getBean().FonctionStockee("RechFilm", "GetDirectorsFromMovie", 1);
            Caller.getBean().csRegisterOutParameter(1, OracleTypes.CURSOR);
            Caller.getBean().csSetString(2, IdMovie);
            rs = Caller.getBean().csFonctionExecute();
            
            while(rs.next())
                tfdRealisateurs.setText(rs.getString(2));
            
            /* Les cotes des utilisateurs RQS */
            FillRQS();
        } 
        catch (SQLException ex)
        {
            if(ex.getErrorCode() == 20999)
                Caller.DatabaseConnection();
            else
                Logger.getLogger(AddOpinionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void FillRQS() throws SQLException
    {
        Caller.getBean().FonctionStockee("RechFilm", "GetQuotationsOpinionsFromRQS", 1);
        Caller.getBean().csRegisterOutParameter(1, OracleTypes.CURSOR);
        Caller.getBean().csSetString(2, IdMovie);
        ResultSet rs = Caller.getBean().csFonctionExecute();

        while(rs.next())
        {
            lblNombreRQS.setText(rs.getString(2));
            lblMoyenneRQS.setText(rs.getString(1));
            NombreCotesAvis = rs.getShort(3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        lblPoster = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarOverview = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        lblIdentifiant = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfdActeurs = new javax.swing.JTextField();
        lblRuntime = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfdRealisateurs = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblMoyenneTMDB = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAfficherAvis = new javax.swing.JButton();
        lblNombreTMDB = new javax.swing.JLabel();
        btnAjouterAvis = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblTitre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblMoyenneRQS = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNombreRQS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Réalisateur(s):");

        jLabel10.setText("Moyenne des votes RQS :");

        txtarOverview.setEditable(false);
        txtarOverview.setColumns(20);
        txtarOverview.setRows(5);
        jScrollPane1.setViewportView(txtarOverview);

        jLabel6.setText("Overview :");

        lblIdentifiant.setText("Identifiant du film : ");

        jLabel11.setText("Nombre de votes RQS :");

        tfdActeurs.setEditable(false);

        lblRuntime.setText("jLabel8");

        jLabel7.setText("Runtime :");

        tfdRealisateurs.setEditable(false);

        jLabel2.setText("Titre :");

        lblId.setText("jLabel13");

        lblDate.setText("jLabel8");

        lblMoyenneTMDB.setText("jLabel12");

        jLabel3.setText("Date de sortie :");

        btnAfficherAvis.setText("Afficher les avis");
        btnAfficherAvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficherAvisActionPerformed(evt);
            }
        });

        lblNombreTMDB.setText("jLabel13");

        btnAjouterAvis.setText("Ajouter un avis");
        btnAjouterAvis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterAvisActionPerformed(evt);
            }
        });

        jLabel8.setText("Moyenne des votes TMDb :");

        lblTitre.setText("jLabel8");

        jLabel4.setText("Acteur(s):");

        lblMoyenneRQS.setText("jLabel12");

        jLabel9.setText("Nombre de votes TMDb :");

        lblNombreRQS.setText("jLabel13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAfficherAvis)
                        .addGap(18, 18, 18)
                        .addComponent(btnAjouterAvis)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfdRealisateurs))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfdActeurs))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblTitre))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblIdentifiant)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblId))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblDate))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblRuntime))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblMoyenneTMDB))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblNombreTMDB))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblMoyenneRQS))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblNombreRQS))
                                            .addComponent(jLabel6))
                                        .addGap(0, 270, Short.MAX_VALUE)))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdentifiant)
                            .addComponent(lblId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTitre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfdActeurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfdRealisateurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblRuntime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblMoyenneTMDB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblNombreTMDB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(lblMoyenneRQS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lblNombreRQS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAfficherAvis)
                    .addComponent(btnAjouterAvis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAfficherAvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfficherAvisActionPerformed
        AvisForm af = new AvisForm(Caller, true, IdMovie, NombreCotesAvis);
        af.setVisible(true);
    }//GEN-LAST:event_btnAfficherAvisActionPerformed

    private void btnAjouterAvisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterAvisActionPerformed
        AddOpinionForm aof = new AddOpinionForm(Caller, true, IdMovie, Login);
        aof.setVisible(true);
        try
        {
            if(aof.isNewQuotation())
                FillRQS();
        }
        catch (SQLException ex)
        {
            if(ex.getErrorCode() == 20999)
                Caller.DatabaseConnection();
            else
                Logger.getLogger(AddOpinionForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAjouterAvisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetailsMovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetailsMovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetailsMovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetailsMovieForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DetailsMovieForm dialog = new DetailsMovieForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAfficherAvis;
    private javax.swing.JButton btnAjouterAvis;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdentifiant;
    private javax.swing.JLabel lblMoyenneRQS;
    private javax.swing.JLabel lblMoyenneTMDB;
    private javax.swing.JLabel lblNombreRQS;
    private javax.swing.JLabel lblNombreTMDB;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblRuntime;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JTextField tfdActeurs;
    private javax.swing.JTextField tfdRealisateurs;
    private javax.swing.JTextArea txtarOverview;
    // End of variables declaration//GEN-END:variables
}
